#环境超参
ROOM_W_GRID_SIZE_LOW = 5
ROOM_W_GRID_SIZE_HIGH = 16
ROOM_L_GRID_SIZE_LOW = 5
ROOM_L_GRID_SIZE_HIGH = 16
CELL_SIZE_LOW = 1.0
CELL_SIZE_HIGH = 3.0
FLOOR_HEIGHT_LOW = 2.0
FLOOR_HEIGHT_HIGH = 8.0
#Convective Heat Transfer Coefficients
INTERNAL_CHTC_LOW = 1.5
INTERNAL_CHTC_HIGH = 25.0
WALL_CHTC_LOW = 1.5
WALL_CHTC_HIGH = 3.0
FLOOR_CHTC_LOW = 2.0
FLOOR_CHTC_HIGH = 6.0
GRID_HC_LOW = 1.3
GRID_HC_HIGH = 2.0
EQUIPMENT_HC_LOW = 200
EQUIPMENT_HC_HIGH = 400
#Distribution of sensors and devices
SENSOR_DENSITY_LOW = 0.10
SENSOR_DENSITY_HIGH = 0.30
HEATER_DENSITY_LOW = 0.10
HEATER_DENSITY_HIGH = 0.30
COOLER_DENSITY_LOW = 0.05
COOLER_DENSITY_HIGH = 0.15
#Distribution of target temperature
TARGET_TEMPERATURE_LOW = 24.0
TARGET_TEMPERATURE_HIGH = 28.0
#Distrbution of the ambient temperature
AMBIENT_TEMPERATURE_LOW = -10.0
AMBIENT_TEMPERATURE_HIGH = [(20, 0.2), (30, 0.3), (40, 0.5)] # A mixture of three uniform distributions: 20-30 with 20% probability, 30-40 with 30% probability, and 40-50 with 50% probability

# 控制传感器漂移
# Drift period (longest), in minutes
SENSOR_DRIFT_PERIOD_LOW =  129600 # 30 days
SENSOR_DRIFT_PERIOD_HIGH = 518400 # 360 days
SENSOR_DRIFT_FOURIER_MAX_ORDER = 3
SENSOR_DRIFT_FOURIER_MAX_ITEMS = 3
SENSOR_DRIFT_UPPER_BOUND = 0.5
SENSOR_DRIFT_MEAN = 0.1

# Configuration of the coolers
# Ventilator
COOLER_VENT_EFFICIENCY_LOW = 0.5
COOLER_VENT_EFFICIENCY_HIGH = 1.0
# Energy Efficiency Ratio (EER)
COOLER_EER_BASE_LOW = 2.0
COOLER_EER_BASE_HIGH = 5.0
# 制冷效率衰减起点, 当温度差超过这个值时，制冷效率开始衰减
COOLER_EER_DECAY_START_LOW = 8.0
COOLER_EER_DECAY_START_HIGH = 15.0
# 制冷效率为0的点, 当温度差超过这个值时，制冷效率为0
COOLER_EER_ZERO_POINT_LOW = 16
COOLER_EER_ZERO_POINT_HIGH = 24
# 当温度差为负时的冷却效率, 这个值越大，表示当温度差为负时，冷却效率越高
COOLER_EER_REVERSE_LOW = 5.0
COOLER_EER_REVERSE_HIGH = 10.0
# Configuration of the impact range of the devices
COOLER_SPACE_INSTANT_DIFFUSION_LOW = 1.0 
COOLER_SPACE_INSTANT_DIFFUSION_HIGH = 4.0
HEAT_SPACE_INSTANT_DIFFSION_LOW = 0.5
HEAT_SPACE_INSTANT_DIFFUSION_HIGH = 1.5
# 空调回风传感器漂移
# Drift period (longest), in minutes
DEVICE_SENSOR_DRIFT_PERIOD_LOW = 10080 # 7 days
DEVICE_SENSOR_DRIFT_PERIOD_HIGH = 129600 # 90 days
DEVICE_SENSOR_DRIFT_FOURIER_MAX_ORDER = 3
DEVICE_SENSOR_DRIFT_FOURIER_MAX_ITEMS = 3
DEVICE_SENSOR_DRIFT_UPPER_BOUND = 5.0
DEVICE_SENSOR_DRIFT_MEAN = 0.5
# 空调控温逻辑
# PID 相关参数
COOLER_DIFF_DECAY_UB_LOW = 0.01
COOLER_DIFF_DECAY_UB_HIGH = 2.0
COOLER_DIFF_DECAY_LB_LOW = -2.0
COOLER_DIFF_DECAY_LB_HIGH = -0.01
# 制冷功率相关参数
COOLER_MAX_COOLING_POWER = 10000
COOLER_POWER_VENT_MIN_LOW = 500
COOLER_POWER_VENT_MIN_HIGH = 1000
COOLER_VENT_FIXED_RATIO_FACTOR = 0.50
COOLER_VENT_FIXED_RATIO_LOW = 0.05
COOLER_VENT_FIXED_RATIO_HIGH = 0.15
COOLER_VENT_FIXED_POWER_LOW = 500
COOLER_VENT_FIXED_POWER_HIGH = 1500


# Configuration of the heat sources
# Determines how much the heat source are correlated to each other, the higher the value, the more correlated the heat sources are, and the easier for the agent to learn the pattern of the heat sources.
HEAT_SOURCE_BASE_FACTOR_LOW = 0.2
HEAT_SOURCE_BASE_FACTOR_HIGH = 0.8
# Default period range of the individual heat sources, in minutes
HEAT_SOURCE_PERIOD_RANGE_LOW = 1440 # A day
HEAT_SOURCE_PERIOD_RANGE_HIGH = 10080 # A week
# Default period range of the basic heat sources, in minutes
BASE_HEAT_SOURCE_PERIOD_RANGE_LOW = 1440 # A day
BASE_HEAT_SOURCE_PERIOD_RANGE_HIGH = 10080 # A week
# Default heat fourier configuration
HEAT_SOURCE_FOURIER_MAX_ORDER = 24 # Default highest frequency: 1440 / 24 = 60 minutes
HEAT_SOURCE_FOURIER_MAX_ITEM = 6 # Number of Fourier items to generate the heat source pattern
# Heat source scale
HEAT_SOURCE_VARIANT_SCALE_LOW = 3200 # 3.2 kW at minimum
HEAT_SOURCE_VARIANT_SCALE_HIGH = 9600 # 9.6 kW at maximum
# Base heat source scale, mimimum power
BASE_HEAT_SOURCE_VARIANT_SCALE_LOW = 500 # 500W at minimum
BASE_HEAT_SOURCE_VARIANT_SCALE_HIGH = 2000 # 2000W at maximum
# Maximum heat source power, which is used to clip the heat source power generated by the heat source function. This is set to a very high value to allow for some extreme cases to test the robustness of the agent, but in general, the heat source power should be much lower than this value.
MAX_HEAT_SOURCE_POWER = 20000 # 20 kW at maximum, which is a very high heat source power, but we want to allow for some extreme cases to test the robustness of the agent.